# This is a basic workflow to help you get started with Actions

name: Build + test Angular

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Configuración del job
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Pasos a ejecutar en la pipeline:
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Saludando al mundo
      run: echo Hola mundo
    
    - name: Instalar Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
      
    - name: Instalar dependencias
      run: npm install

    - name: Compilar app
      run: npm run build -- --prod

    #- name: Ejecutar tests
    #  run: npm run test-headless
